### ISSUE TITLE
Pull requests merge without Review/approval?

### ISSUE THREAD

**Issue by bhaumikmistry** [annahinnyc/code4good-accessibility#16]
### Issue with Pull request merge
Currently any/all pull requests does not require a review/approval?

### Why review required?
Reviews allow for discussion of proposed changes and help ensure that the changes meet the repository's contributing guidelines and other quality standards.

### Solution
- Add a pull request template to .github directory [Example](https://github.com/stevemao/github-issue-templates/blob/master/checklist/PULL_REQUEST_TEMPLATE.md)
- Enforce the template usage in while creating a PR
- Enforce/require review or approval before merge

**Comment by annahinnyc** [comment]
Fantastic!  Would you have bandwidth to add the template?

**Comment by bhaumikmistry** [comment]
I’ll get on it!!

**Comment by bhaumikmistry** [comment]
@annahinnyc PR created!!
